import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
// Importar tipografia Montserrat desde googlefonts
import "./globals.css";
// Importar estilos globales
import Navbar from "./components/navbar";

const monserrat = Montserrat({ subsets: ["latin"] });
// Usar Montserrat a traves de todo el sitio

export const metadata: Metadata = {
  title: "Pokedex with NextJS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={monserrat.className}>
        <Navbar />
        {/* instancia de componente Navbar*/}
        {children}
      </body>
    </html>
  );
}
